cloudwego/pilota

Cargo.lock
pilota-build/Cargo.toml
pilota-build/src/parser/thrift/mod.rs

fix: path canonicalize

---

Cargo.lock
pilota-build/Cargo.toml
pilota-build/src/codegen/thrift/mod.rs
pilota-build/test_data/thrift/enum_test.rs
pilota-build/test_data/thrift/enum_test.thrift
pilota-build/test_data/thrift/normal.rs
pilota-build/test_data/thrift/recursive_type.rs
pilota-thrift-parser/Cargo.toml
pilota-thrift-parser/src/parser/constant.rs

fix: parse hex digit

---

pilota-build/src/parser/protobuf/mod.rs

Fix when .proto file changed but program not correctly build

fix pb rerun-if-changed

---

pilota-build/src/parser/thrift/mod.rs

fix: cargo rerun cache

---

Cargo.lock
pilota-build/Cargo.toml
pilota-build/src/parser/protobuf/mod.rs

fix: print cargo rerun for pb

---

pilota-build/src/codegen/mod.rs
pilota-build/src/codegen/thrift/mod.rs
pilota-build/src/db.rs
pilota-build/src/middle/rir.rs
pilota-build/src/resolve.rs
pilota/src/lib.rs
pilota/src/thrift/binary.rs
pilota/src/thrift/error.rs
pilota/src/thrift/mod.rs
pilota/src/thrift/rw_ext.rs

ApplicationError is protocol-agnostic

fix: remove ApplicationError

---

Cargo.lock
pilota-build/Cargo.toml
pilota-build/src/codegen/mod.rs
pilota-build/src/db.rs
pilota-build/src/lib.rs
pilota-build/src/parser/mod.rs
pilota-build/src/parser/protobuf/mod.rs
pilota-build/src/parser/thrift/mod.rs
pilota-build/src/test/mod.rs
pilota-build/test_data/must_gen_items.rs
pilota-build/test_data/must_gen_items.thrift

some unused items by idl `Service` may be used by user's code
add `must_gen_items` to generate  unused items

feat: must gen items for thrift

---

pilota-build/src/lib.rs
pilota-build/src/symbol.rs
pilota-thrift-parser/src/parser/struct_.rs

pub IdentName

---

pilota-build/src/codegen/thrift/mod.rs
pilota-build/src/symbol.rs
pilota-build/test_data/must_gen_items.rs
pilota-build/test_data/thrift/normal.rs
pilota-build/test_data/thrift/pilota_name.rs
pilota-build/test_data/thrift/recursive_type.rs
pilota-build/test_data/thrift/self_kw.rs
pilota-build/test_data/thrift/self_kw.thrift

fix: generate keyword

---

pilota-build/src/codegen/mod.rs
pilota-build/src/ir/mod.rs
pilota-build/src/middle/rir.rs
pilota-build/src/middle/ty.rs
pilota-build/src/parser/protobuf/mod.rs
pilota-build/src/parser/thrift/mod.rs
pilota-build/src/resolve.rs
pilota-build/test_data/protobuf/nested_message.proto
pilota-build/test_data/protobuf/nested_message.rs

fix: naming resolve for protobuf

fix: naming resolve for protobuf

---

pilota-build/src/codegen/thrift/mod.rs
pilota-build/src/codegen/thrift/ty.rs
pilota-build/test_data/must_gen_items.rs
pilota-build/test_data/thrift/const_val.rs
pilota-build/test_data/thrift/enum_test.rs
pilota-build/test_data/thrift/normal.rs
pilota-build/test_data/thrift/pilota_name.rs
pilota-build/test_data/thrift/recursive_type.rs
pilota-build/test_data/thrift/self_kw.rs
pilota/src/thrift/error.rs
pilota/src/thrift/mod.rs

remove triat `Size`

---

pilota-build/src/codegen/thrift/mod.rs
pilota-build/test_data/thrift/const_val.rs
pilota-build/test_data/thrift/enum_test.rs
pilota-build/test_data/thrift/self_kw.rs
pilota/src/thrift/binary.rs
pilota/src/thrift/rw_ext.rs

optimize: encode performance
1.  inline `write_field_begin`
2. remove `unwrap` by `if let Some(id) = identifier.id`

optimize: encode performance

---

pilota-build/src/codegen/thrift/mod.rs
pilota-build/test_data/thrift/const_val.rs
pilota-build/test_data/thrift/enum_test.rs
pilota-build/test_data/thrift/self_kw.rs

fix: can not find `value` for read enum

fix: can not find `value` for read enum

---

pilota-build/src/codegen/thrift/mod.rs
pilota-build/test_data/must_gen_items.rs
pilota-build/test_data/thrift/normal.rs
pilota-build/test_data/thrift/pilota_name.rs
pilota-build/test_data/thrift/recursive_type.rs
pilota-build/test_data/thrift/self_kw.rs
pilota/src/thrift/binary.rs
pilota/src/thrift/mod.rs

remove unnecessary write field stop in `write_field_begin`

remove write field stop

---

Cargo.lock
pilota-build/Cargo.toml
pilota-build/src/codegen/mod.rs
pilota-thrift-parser/Cargo.toml
pilota/Cargo.toml

bump version

---

pilota-build/src/lib.rs

fix: hash derive

---

pilota-build/src/parser/thrift/mod.rs

remove `println`

---

Cargo.lock
pilota-build/Cargo.toml
pilota-build/src/resolve.rs
pilota-build/test_data/protobuf/bytes_vec.rs
pilota-build/test_data/thrift/binary_vec.rs

generate `Bytes` type for thrift binary and protobuf bytes

generate `Bytes` type for thrift binary and protobuf bytes

---

pilota-build/src/lib.rs
pilota-build/src/parser/protobuf/mod.rs
pilota-build/src/plugin/mod.rs
pilota-build/test_data/thrift/const_val.rs
pilota-build/test_data/thrift/enum_test.rs
pilota-build/test_data/thrift/self_kw.rs

feat: don't generate unused item for protobuf

feat: don't generate unused item for protobuf

---

pilota-build/src/parser/thrift/mod.rs
pilota-build/test_data/thrift/pilota_name.rs
pilota-build/test_data/thrift/pilota_name.thrift
pilota-thrift-parser/src/descriptor/constant.rs
pilota-thrift-parser/src/descriptor/struct_.rs
pilota-thrift-parser/src/descriptor/typedef.rs
pilota-thrift-parser/src/parser/constant.rs
pilota-thrift-parser/src/parser/struct_.rs
pilota-thrift-parser/src/parser/typedef.rs

extract tags from thrift item

---

pilota-build/src/codegen/mod.rs
pilota-build/src/lib.rs
pilota-build/src/middle/context.rs

fix: collect pb used items

---

pilota-build/src/codegen/mod.rs
pilota-build/src/plugin/mod.rs
pilota-build/test_data/thrift/const_val.rs
pilota-build/test_data/thrift/enum_test.rs
pilota-build/test_data/thrift/pilota_name.rs
pilota-build/test_data/thrift/pilota_name.thrift
pilota-build/test_data/thrift/self_kw.rs

fix: codegen name for const

---

pilota-build/src/parser/thrift/mod.rs

fix: duplicated method args and result

fix: duplicated method args and result

---

pilota-build/src/parser/thrift/mod.rs
pilota-build/src/plugin/mod.rs
pilota-build/test_data/thrift/const_val.rs
pilota-build/test_data/thrift/enum_test.rs
pilota-build/test_data/thrift/pilota_name.rs
pilota-build/test_data/thrift/pilota_name.thrift
pilota-build/test_data/thrift/self_kw.rs
pilota-thrift-parser/src/descriptor/enum_.rs
pilota-thrift-parser/src/parser/enum_.rs

fix: enum variant annotations

---

pilota-build/src/lib.rs
pilota-build/src/middle/context.rs
pilota-build/src/parser/protobuf/mod.rs
pilota-build/src/test/mod.rs

feat: support touch

---

pilota-build/src/codegen/protobuf/mod.rs
pilota-build/src/middle/ty.rs

fix: replace enum to i32 for pb

fix: replace enum to i32 for pb

---

pilota-build/src/codegen/mod.rs
pilota-build/src/middle/ty.rs
pilota-build/test_data/thrift/const_val.rs
pilota-build/test_data/thrift/const_val.thrift

support array const

---

pilota-build/src/plugin/mod.rs
pilota-build/test_data/thrift/const_val.rs
pilota-build/test_data/thrift/enum_test.rs
pilota-build/test_data/thrift/pilota_name.rs
pilota-build/test_data/thrift/self_kw.rs

fix: name conflict

---

pilota-build/src/codegen/mod.rs
pilota-build/src/middle/ty.rs
pilota-build/test_data/thrift/const_val.rs

fix: gen const array

---

pilota-build/src/codegen/mod.rs
pilota-build/src/parser/protobuf/mod.rs
pilota-build/src/parser/thrift/mod.rs

pub newtype constructor

---

pilota-build/src/resolve.rs

report errors

---

Cargo.lock
pilota-build/src/codegen/mod.rs
pilota-build/src/codegen/thrift/decode_helper.rs
pilota-build/src/codegen/thrift/ty.rs
pilota-build/test_data/thrift/binary_bytes.rs
pilota-build/test_data/thrift/binary_vec.rs
pilota-build/test_data/thrift/pilota_name.rs
pilota-build/test_data/thrift/self_kw.rs
pilota-build/test_data/thrift/wrapper_arc.rs
pilota/Cargo.toml
pilota/src/thrift/binary.rs
pilota/src/thrift/mod.rs

Note: This is a BREAK CHANGE, so will need to draft a new major release.

feat: support zerocopy thrift protocol

---

pilota-build/src/parser/protobuf/mod.rs

fix: remove unused oneof_decl

---

pilota-build/src/parser/protobuf/mod.rs
pilota-build/test_data/protobuf/bytes.rs
pilota-build/test_data/protobuf/nested_message.rs
pilota-build/test_data/protobuf/optional.proto
pilota-build/test_data/protobuf/optional.rs
pilota-build/test_data/protobuf/string.rs

fix: optional in proto

---

pilota-build/src/parser/protobuf/mod.rs
pilota-build/test_data/protobuf/bytes.rs

fix bytes optional

---

pilota-build/src/parser/protobuf/mod.rs
pilota-build/test_data/protobuf/string.proto
pilota-build/test_data/protobuf/string.rs

fix: proto3 optional

---

pilota-build/src/codegen/mod.rs
pilota-build/src/codegen/thrift/mod.rs
pilota-build/src/codegen/thrift/ty.rs
pilota-build/src/middle/ty.rs
pilota-build/src/resolve.rs
pilota-build/src/tags.rs
pilota-build/test_data/thrift/wrapper_arc.rs
pilota-build/test_data/thrift/wrapper_arc.thrift

feat: arc warpper for container type

WIP: arc warpper for container type
